run tests using PHPUnit 11.5

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -75,7 +75,7 @@ jobs:
           ([ -d "$COMPOSER_HOME" ] || mkdir "$COMPOSER_HOME") && cp .github/composer-config.json "$COMPOSER_HOME/config.json"
 
           echo COLUMNS=120 >> $GITHUB_ENV
-          echo PHPUNIT="$(pwd)/phpunit --exclude-group tty,benchmark,intl-data,integration,transient" >> $GITHUB_ENV
+          echo PHPUNIT="$(pwd)/phpunit --exclude-group tty --exclude-group benchmark --exclude-group intl-data --exclude-group integration --exclude-group transient" >> $GITHUB_ENV
           echo COMPOSER_UP='composer update --no-progress --ansi'$([[ "${{ matrix.mode }}" != low-deps ]] && echo ' --ignore-platform-req=php+') >> $GITHUB_ENV
 
           SYMFONY_VERSIONS=$(git ls-remote -q --heads | cut -f2 | grep -o '/[1-9][0-9]*\.[0-9].*' | sort -V)
@@ -131,7 +131,7 @@ jobs:
           fi
 
           # Legacy tests are skipped when deps=high and when the current branch version has not the same major version number as the next one
-          [[ "${{ matrix.mode }}" = high-deps && $SYMFONY_VERSION = *.4 ]] && echo LEGACY=,legacy >> $GITHUB_ENV || true
+          [[ "${{ matrix.mode }}" = high-deps && $SYMFONY_VERSION = *.4 ]] && echo LEGACY=" --exclude-group legacy" >> $GITHUB_ENV || true
 
           echo SYMFONY_VERSION=$SYMFONY_VERSION >> $GITHUB_ENV
           echo COMPOSER_ROOT_VERSION=$SYMFONY_VERSION.x-dev >> $GITHUB_ENV
@@ -197,13 +197,13 @@ jobs:
           fi
 
           if [[ "${{ matrix.mode }}" = low-deps ]]; then
-            echo "$COMPONENTS" | xargs -n1 | parallel -j +3 "_run_tests {} 'cd {} && $COMPOSER_UP --prefer-lowest --prefer-stable && $PHPUNIT'"
+            echo "$COMPONENTS" | xargs -n1 | parallel -j +3 "_run_tests {} 'cd {} && $COMPOSER_UP --prefer-lowest --prefer-stable && $PHPUNIT --do-not-fail-on-deprecation'"
 
             exit 0
           fi
 
           # matrix.mode = high-deps
-          echo "$COMPONENTS" | xargs -n1 | parallel -j +3 "_run_tests {} 'cd {} && $COMPOSER_UP && $PHPUNIT$LEGACY'" || X=1
+          echo "$COMPONENTS" | xargs -n1 | parallel -j +3 "_run_tests {} 'cd {} && $COMPOSER_UP && $PHPUNIT$LEGACY --do-not-fail-on-deprecation'" || X=1
 
           # get a list of the patched components (relies on .github/build-packages.php being called in the previous step)
           PATCHED_COMPONENTS=$(git diff --name-only src/ | grep composer.json || true)
@@ -222,7 +222,7 @@ jobs:
                 echo "::group::install phpunit"
                 ./phpunit install
                 echo "::endgroup::"
-                echo "$PATCHED_COMPONENTS" | parallel -j +3 "_run_tests {} 'cd {} && rm composer.lock vendor/ -Rf && $COMPOSER_UP && $PHPUNIT$LEGACY'" || X=1
+                echo "$PATCHED_COMPONENTS" | parallel -j +3 "_run_tests {} 'cd {} && rm composer.lock vendor/ -Rf && $COMPOSER_UP && $PHPUNIT --exclude-group tty,benchmark,intl-data,integration,transient,legacy'" || X=1
               fi
           fi
 
@@ -250,12 +250,12 @@ jobs:
 
           mkdir -p /opt/php/lib
           echo memory_limit=-1 > /opt/php/lib/php.ini
-          ./build/php/bin/php ./phpunit --colors=always src/Symfony/Component/Process
+          ./phpunit install
+          ./build/php/bin/php ./phpunit src/Symfony/Component/Process
 
-      - name: Run PhpUnitBridge tests with PHPUnit 11
+      - name: Run PhpUnitBridge tests with PHPUnit 9.6
         if: '! matrix.mode'
         run: |
           ./phpunit src/Symfony/Bridge/PhpUnit
         env:
-          SYMFONY_PHPUNIT_VERSION: '11.3'
-          SYMFONY_DEPRECATIONS_HELPER: 'disabled'
+          SYMFONY_PHPUNIT_VERSION: '9.6'
